### ISSUE TITLE
타임라인 화면 마크업 및 구현

### ISSUE THREAD

**Issue by myoungS2** [myoungS2/pmq_project_211013#7]
- [x] 타임라인 화면 마크업

**Comment by myoungS2** [comment]
1. header/ section
2. 각각의 div에 edition thumnail 담아서 보여주기
3. 로그인/ 회원가입 view로 넘어가기
4. 검색기능

**Comment by myoungS2** [comment]
userRole이 publisher일 때만 "발행시작" btn보여주기

**Comment by myoungS2** [comment]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Thu Nov 04 01:08:15 KST 2021
There was an unexpected error (type=Internal Server Error, status=500).
Cannot invoke "java.lang.Integer.intValue()" because "userId" is null
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "userId" is null
	at com.pmq.timeline.TimelineController.timelineView(TimelineController.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at 

- [ ] 로그인 되지 않은 상태에서도 타임라인 볼 수 있게?

**Comment by myoungS2** [comment]
와..진짜 3분이 30년같았는데 방금...
불필요한 timelineRestController삭제하려다가
editionController를 지워서 바로 소스트리에서 pull받고 refresh해도 파일이 복원되지 않았다...
진짜 큰일났다 파일 다 꼬이겠다..했는데
검색해보니까 아주 간단한 방법으로 지웠던 파일 다시 살릴 수 있는 기능이 있었다.
그래 어떤 개발자도 나같은 실수를 할 수 있겠구나..싶었고 지금 등에 식은땀 났다..휴...

https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=since201109&logNo=220090233466
